services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    volumes:
      - git_data:/data
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

  # 
  # 
  # This service is used to restore the database from a backup
  # 
  # 

  restore:
    image: ipedrazas/goose:latest
    # Apply all migrations
    command: ["goose", "-dir", "/data/migrations", "up"]
    volumes:
      - tmp_data:/data
    environment:
      - GOOSE_DBSTRING=""
      - GOOSE_DRIVER=postgres
    depends_on:
      data-pull:
          condition: service_completed_successfully
    profiles:
      - ops

  data-pull:
    image: ipedrazas/ktools:latest
    user: root
    working_dir: /data
    env_file:
      - .env
    command: oras pull registry-1.docker.io/$HUB_USER/api-db-oci:latest
    volumes:
      - tmp_data:/data
    depends_on:
      - db
    profiles:
      - ops




volumes:
  db_data:
  